### PR TITLE
[WIP] Mockup

### PR DESCRIPTION
**Pull request by thangngoc89**
Working on a mockup for further development

image

### CODE REVIEW

**Comment by luuhoangnam** [comment]
Let's make the textbox is bigger and form is verticle, not horizontal

**Comment by thangngoc89** [comment]
There you go
image

height = 40em

**Comment by thangngoc89** [comment]
@luuhoangnam  do you know why `gulp watch` doesn't auto trigged versioning? only sass was complied

**Comment by luuhoangnam** [comment]
1__gulp_watch__node_
This is the reason why :+1:

**Comment by luuhoangnam** [comment]
@thangngoc89  And be careful, each time you change `gulpfile.js` content, you must rerun gulp watch

**Comment by thangngoc89** [comment]
@luuhoangnam I don't have that error on my machine.Did you get bootstrap in complied css

**Comment by luuhoangnam** [comment]
I dont know, may be an error

**Comment by thangngoc89** [comment]
may be I should use absoulute path

**Comment by thangngoc89** [comment]
That's cause by missing bower installation in create script 
Fixed https://github.com/Larask/gist/commit/760b018634ca9f95247114cc9336e0a5d55921da

**Pull request merged**
